@startuml

    state "회원 인증 시스템" as Auth {
        [*] --> Idle
        Idle --> CheckingMember : 회원 조회()
        CheckingMember --> CheckingPermissions : 회원 확인
        CheckingPermissions --> Authenticated : 권한 확인
        CheckingMember --> Error : 회원 조회 실패
        CheckingPermissions --> Error : 권한 조회 실패
        Error --> Idle : 초기
    }

    state "Library System" as LS {
        [*] --> Idle
        Idle --> CheckingBook : 대출 가능여부 확인()
        CheckingBook --> Lending : 대출 가능
        Lending --> Idle : 대출 완료
        CheckingBook --> Error : 대출 실패
        Error --> Idle : Reset
    }

Auth : Authenticated --> LS : 사용자인증

@enduml
